TicketApp/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ticket.urls')),
    path('u/', include('users.urls')),
    path('i18n/', include('django.conf.urls.i18n')), #translation url
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Serving the media files in development mode
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

ticket/urls.py
from django.urls import path
from . import views

app_name = 'ticket'
urlpatterns = [
    path('', views.home, name = 'home'),
    path('guide/', views.guide,name ='guide')
]

users/urls.py
from . import views
from django.urls import path


app_name = 'users'
urlpatterns = [
    path('login/', views.login, name = 'login'),
    path('logout/', views.logout, name ='logout'),
    #path('register/', views.register, name ='register'),
    path('register_success/', views.register_success, name ='register_success'),
    path('profile/',views.user_profile,name="user_profile"),
    path('change-password/',views.change_password,name="change_password"),
    path('verify-email/', views.verify_email,name='verify_email'),
    path('confirm-email/<key>',views.confirm_email,name='confirm_email'),
    path('forgot-password/',views.forgot_password,name='forgot_password'),
    path('reset-password/<key>',views.reset_password,name='reset_password'),
]

users/views.py
from datetime import datetime, timedelta, timezone
from django.http import HttpResponseNotFound, HttpResponseRedirect
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib import messages
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.models  import User
from django.core.mail import get_connection
from django.urls import reverse
from users.forms import ChangePasswordForm, RegisterForm, ForgotPasswordForm, ResetPasswordForm, UserProfileForm, VerifyEmailForm
from users.methods import get_client_ip, random_string_generator, send_email
from users.models import UserExtend
from django.utils.translation import gettext as _
from django.conf import settings

import logging
Logger = logging.getLogger("login_log")
# Create your views here.
def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = User(username = form.cleaned_data.get('username'), first_name = form.cleaned_data.get('first_name'), last_name = form.cleaned_data.get('last_name'), email = form.cleaned_data.get('email'))
            user.set_password(str(form.cleaned_data.get('password')))            
            
            userextend =UserExtend(user_id = user,phone_number = form.cleaned_data.get('phone_number'),
                                   birthdate = form.cleaned_data.get('birthdate'),
                                   address= form.cleaned_data.get('address'), parish = form.cleaned_data.get('parish'),
                                   activation_key = random_string_generator(length=15),
                                   key_expires = datetime.now() + timedelta(days=1))
            user.save()
            userextend.save()
            #Send mail to verify email function
            connection = get_connection(host=settings.GMAIL_HOST,port=settings.GMAIL_PORT,username=settings.GMAIL_HOST_USER, password=settings.GMAIL_HOST_PASSWORD,use_tls=settings.GMAIL_USE_TLS)
            subject =_('Xác nhận email!')
            template ='users/verify_email_template.html'
            verify_link = request.scheme + '://' + request.get_host() +'/u/confirm-email/' + user.userextend.activation_key
            home_link = settings.DOMAIN_NAME
            from_email ='GioiTreSaiGon Admin'
            to_emails=[]
            to_emails.append(user.email)
            bcc =[]
            bcc.append('dhgttgpsaigon@gmail.com')
            merge_data = {
                'fullname':user.last_name + ' ' + user.first_name,
                'verify_link':verify_link,
                'home_link':home_link,
            }
            send_email(template,subject,to_emails,merge_data,connection,from_email=from_email,bcc=bcc)
            return HttpResponseRedirect(reverse('users:register_success'))
        else:
            return render(request,'users/register.html',{'form':form})
    else:
        form = RegisterForm()
        return render(request,'users/register.html',{'form':form})

def register_success(request):
    return render(request,'users/register_success.html')

def user_profile(request):
    if not request.user.is_authenticated:
        messages.warning(request,_('Xin vui lòng đăng nhập.'))
        return render(request,'users/login.html')
    if request.method == 'POST':
        form = UserProfileForm(request.POST)
        if form.is_valid():
            user = User.objects.get(username = request.user.username)
            user.last_name = form.cleaned_data.get('last_name')
            user.first_name = form.cleaned_data.get('first_name')
            user.userextend.phone_number = form.cleaned_data.get('phone_number')
            user.userextend.birthdate = form.cleaned_data.get('birthdate')
            user.userextend.address = form.cleaned_data.get('address')
            user.userextend.parish = form.cleaned_data.get('parish')
            user.save()
            user.userextend.save()
            messages.success(request,_('Đã Lưu'))
            return render(request,'users/user_profile.html',{'form':form})
        else:
            return render(request,'users/user_profile.html',{'form':form})
    else:
        user = User.objects.get(username = request.user.username)
        form = UserProfileForm({'username' : user.username,
                                'first_name':user.first_name,
                                'last_name':user.last_name,
                                'email':user.email,
                                'phone_number':user.userextend.phone_number,
                                'birthdate':user.userextend.birthdate,
                                'address':user.userextend.address,
                                'parish':user.userextend.parish})
        return render(request,'users/user_profile.html',{'form':form})

def change_password(request):
    if not request.user.is_authenticated:
        messages.warning(request,_('Xin vui lòng đăng nhập.'))
        return render(request,'users/login.html')
    if request.method == 'POST':
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            old_password = form.cleaned_data.get('old_password')
            user = User.objects.filter(username = request.user.username).first()
            if not user.check_password(old_password):
                messages.warning(request,_('Mật khẩu cũ không chính xác.'))
                return render(request,'users/change_password.html',{'form':form})
            new_password = form.cleaned_data.get('new_password')
            user.set_password(new_password)
            user.save()
            messages.success(request,_('Thay đổi mật khẩu thành công.'))
            return render(request,'users/change_password.html',{'form':form})
        else:
            return render(request,'users/change_password.html',{'form':form})
    else:
        form = ChangePasswordForm()
        return render(request,'users/change_password.html',{'form':form})

def login(request):
    if request.user.is_authenticated:
        return redirect('ticket:home')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        client_ip = get_client_ip(request)
        user = authenticate(request, username = username, password = password)
        if user is not None:
            auth_login(request, user)         
            Logger.info(f'{client_ip} pass {username}')
            #if user's email is not verified
            if not user.userextend.is_email_verified:
                messages.warning(request,_('Tài khoản chưa xác nhận email. Bạn vui lòng xác nhận email để đăng nhập.'))
                return redirect('users:verify_email')
            return HttpResponseRedirect(reverse('ticket:home'))
        else:
            Logger.warning(f'{client_ip} fail {username}')
            messages.warning(request,_('Tài khoản/Mật khẩu không chính xác!'))
            return render(request,'users/login.html')
    else:
        messages.warning(request,'Hiện chúng tôi đã đóng link đăng ký. Nếu bạn chưa chọn vé workshop, bạn vẫn có thể đăng nhập để chọn vé.')
        return render(request,'users/login.html')

def logout(request):
	if request.method == 'POST':
		auth_logout(request)		
		return redirect('users:login')

#verify email for user try to log in
def verify_email(request):
    if not request.user.is_authenticated:
        messages.warning(request,_('Xin vui lòng đăng nhập.'))
        return render(request,'users/login.html')
        
    user = User.objects.get(username = request.user.username)
    #if user's email already verified
    if user.userextend.is_email_verified:
        return redirect('ticket:home')

    if request.method == 'POST':
        form = VerifyEmailForm(request.POST)
        if form.is_valid():
            # Check if mail is sent recently (1 minute)
            if user.userextend.key_expires is not None:
                minutes_ago = datetime.now(timezone(timedelta(hours=+0))) - timedelta(minutes=1)
                key_created_date = user.userextend.key_expires - timedelta(days=1)
                if minutes_ago < key_created_date:
                    messages.warning(request,_('Mail vừa được gửi mới đây, xin vui lòng chờ.'))
                    return render(request,'users/verify_email.html',{'form':form})  
            email = form.cleaned_data.get('email') 
            user.email = email
            user.userextend.activation_key = random_string_generator(length=15)
            user.userextend.key_expires = datetime.now() + timedelta(days=1)            
            user.save()
            user.userextend.save()

            #Send mail to verify email function
            connection = get_connection(host=settings.GMAIL_HOST,port=settings.GMAIL_PORT,username=settings.GMAIL_HOST_USER, password=settings.GMAIL_HOST_PASSWORD,use_tls=settings.GMAIL_USE_TLS)
            subject =_('Xác nhận email!')
            template ='users/verify_email_template.html'
            verify_link = request.scheme + '://' + request.get_host() +'/u/confirm-email/' + user.userextend.activation_key
            home_link = settings.DOMAIN_NAME
            from_email ='GioiTreSaiGon Admin'
            to_emails=[]
            to_emails.append(user.email)
            bcc =[]
            bcc.append('dhgttgpsaigon@gmail.com')
            merge_data = {
                'fullname':user.last_name + ' ' + user.first_name,
                'verify_link':verify_link,
                'home_link':home_link,
            }
            send_email(template,subject,to_emails,merge_data,connection,from_email=from_email,bcc=bcc)
            messages.success(request,_('Đã gửi mail xác nhận. Xin vui lòng kiểm tra email.'))
            return HttpResponseRedirect(reverse('users:verify_email'))
        else:
            return render(request,'users/verify_email.html',{'form':form})       
    else:
        form = VerifyEmailForm()

users/templates/users/base.html
<!DOCTYPE html>
<html>

<head>
    {% load tz %}
    {% load i18n %}
    {% load static %}
    <!-- Jquery -->
    <script type="text/javascript" src="{% static 'jquery/jquery-3.6.1.min.js' %}"></script>
    <!-- Materialize-->
    <!-- <script src="{% static 'materialize/js/materialize.min.js' %}"></script>
    <link type="text/css" rel="stylesheet" href="{% static 'materialize/css/materialize.min.css' %}" media="screen,projection" /> -->

    <!-- Bootstrap-->   
    <link text="text/css" rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">  
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta property="og:image" content="{% static '/images/logo.png' %}"/>
</head>
<header>
    {% block header %}
    {% if user.is_authenticated %}
    <nav class="navbar navbar-dark bg-primary navbar-expand-lg fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'ticket:home' %}"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ticket:home' %}">{% trans 'Trang chủ' %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" target="_blank" href="https://gioitresaigon.net/huong-dan-mua-ve-dhgt-2022.html">{% trans 'Hướng dẫn mua vé' %}</a>
                    </li> 
                </ul>
                <ul class="navbar-nav mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link">{% trans 'Vé Workshop' %}: {{ user.userextend.special_ticket }}</a>
                    </li>

                    <li class="nav-item dropdown me-auto mb-2 mb-lg-0">
                        <a class="nav-link dropdown-toggle" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{ user.get_username }}</a>
                        <ul class="dropdown-menu dropdown-menu-end">
                            <li>
                                <li><a class="dropdown-item" href="{% url 'users:user_profile' %}">{% trans 'Thông tin cá nhân' %}</a></li>
                                <li><a class="dropdown-item" href="{% url 'users:change_password' %}">{% trans 'Đổi mật khẩu' %}</a></li>
                                <li>
                                    <form id="logout-form" name="logout" method="post" action="{% url 'users:logout' %}">
                                        {% csrf_token %}
                                        <a class="dropdown-item" name="logout" onclick="document.forms['logout-form'].submit();">{% trans 'Đăng xuất' %}</a>
                                    </form>
                                    
                                </li>
                            </li>                                                                                          
                        </ul>
                    </li>                   
                </ul>
            </div>
        </div>
    </nav>

    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasNavbarLabel"></h5>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'ticket:home' %}">{% trans 'Trang chủ' %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" target="_blank" href="https://gioitresaigon.net/huong-dan-mua-ve-dhgt-2022.html">{% trans 'Hướng dẫn mua vé' %}</a>
            </li> 
            <li class="nav-item dropdown me-auto mb-2 mb-lg-0">
                <a class="nav-link dropdown-toggle" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{ user.get_username }}</a>
                <ul class="dropdown-menu dropdown-menu-end">
                    <li>
                        <li><a class="dropdown-item" href="{% url 'users:user_profile' %}">{% trans 'Thông tin cá nhân' %}</a></li>
                        <li><a class="dropdown-item" href="{% url 'users:change_password' %}">{% trans 'Đổi mật khẩu' %}</a></li>
                        <li>
                            <form id="logout-form" name="logout" method="post" action="{% url 'users:logout' %}">
                                {% csrf_token %}
                                <a class="dropdown-item" name="logout" onclick="document.forms['logout-form'].submit();">{% trans 'Đăng xuất' %}</a>
                            </form>
                            
                        </li>
                    </li>                                                                                          
                </ul>
            </li>
            <li class="nav-item">
                <a class="nav-link">{% trans 'Vé Workshop' %}: {{ user.userextend.special_ticket }}</a>
            </li> 
          </ul>
        </div>
    </div>
    {% else %}
    <nav class="navbar navbar-dark bg-primary navbar-expand-lg fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'ticket:home' %}"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ticket:home' %}">{% trans 'Trang chủ' %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" target="_blank" href="https://gioitresaigon.net/huong-dan-mua-ve-dhgt-2022.html">{% trans 'Hướng dẫn mua vé' %}</a>
                    </li>                 
                </ul>
                <ul class="navbar-nav mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">{% trans 'Đăng nhập' %}</a>
                    </li>
                    <li class="nav-item">
                        
                    </li>
                </ul>                                     
            </div> 
        </div>
    </nav>

    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasNavbarLabel"></h5>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'ticket:home' %}">{% trans 'Trang chủ' %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" target="_blank" href="https://gioitresaigon.net/huong-dan-mua-ve-dhgt-2022.html">{% trans 'Hướng dẫn mua vé' %}</a>
            </li> 
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">{% trans 'Đăng nhập' %}</a>
            </li>
            <li class="nav-item">
                
            </li>
          </ul>
        </div>
    </div>
    {% endif %}
    {% endblock %}
</header>

<body>
    {% block content %}
    {% endblock %}
</body>
</html>

users/templates/users/forgot_password.html
{% extends "users/base.html" %}
{% load i18n %}
{% block content %}
<section class="vh-100" style="background-image: url('/static/images/hero_1.png');">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                <div class="card shadow-2-strong" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">
                        <h3 class="mb-5">Quên mật khẩu?</h3>
                        <form method="POST" action="{% url 'users:forgot_password' %}">
                            {% csrf_token %}
                            {% if messages %}
                                {% for message in messages %}
                                    {% if message.tags == 'success'%}
                                        <span class="text-success">{{ message }}</span>
                                    {% else %}
                                        <span class="text-danger">{{ message }}</span>
                                    {% endif %}
                                {% endfor %}
                            {% endif %}
                            
                            {% for field in form.visible_fields %}                          
                            <div class="form-floating mb-4"> 
                                {{ field }}
                                <label for="{{ field.name }}">{{ field.label }}</label>  
                                {% if field.errors %}
                                    {% for err  in field.errors %}
                                        <span class="text-danger">{{ err }}</span>
                                    {% endfor %}
                                {% endif %}
                            </div>
                            <div class="form-floating mb-4">
                                {% endfor %}                                                         
                            {% if form.non_field_errors %}
                                {% for err in form.non_field_errors %}
                                    <span class="text-danger">{{ err }}</span>
                                {% endfor %}
                            {% endif %}
                            </div>
                            <button class="btn btn-primary btn-lg btn-block" type="submit">{% trans 'Gửi Email' %}</button>                      
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

users/templates/users/login.html
{% extends 'users/base.html' %}
{% load i18n %}
{% load static %}
{% block content %}

<section class="vh-100" style="background-image: url('/static/images/hero_1.png');">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                <div class="card shadow-2-strong" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">
                        <h3 class="mb-5">{% trans 'Đăng nhập' %}</h3>
                        <form method="POST" , action="{% url 'users:login' %}">
                            {% csrf_token %}
                            {% if messages %}
                                {% for message in messages %}
                                    {% if message.tags == 'success'%}
                                        <p class="text-success">{{ message }}</p>
                                    {% else %}
                                        <p class="text-danger">{{ message }}</p>
                                    {% endif %}
                                {% endfor %}
                            {% endif %}
                            <div class="form-floating mb-4">                               
                                <input class="form-control" type="text" name="username" id="username" placeholder="{% trans 'Tài khoản' %}"/>   
                                <label for="username">{% trans 'Tài khoản' %}</label>                           
                            </div>
                            <div class="form-floating mb-4">
                                <input type="password" id="password" name="password" class="form-control" placeholder="{% trans 'Mật khẩu' %}" />
                                <label for="password">{% trans 'Mật khẩu' %}</label>
                            </div>
                            <button class="btn btn-primary btn-lg btn-block" type="submit">{% trans 'Đăng nhập' %}</button>                      
                        </form>
                        <hr class="my-4">
                        <a href="{% url 'users:forgot_password' %}">{% trans 'Bạn đã quên mật khẩu?' %}</a> 
                        <br>                       
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

users/templates/users/user_profile.html
{% extends "users/base.html" %}
{% load i18n %}
{% load static %}
{% block content %}
<div class="bg-image"
    style="background-image: url('/static/images/hero_1.png'); background-size: cover;background-repeat: no-repeat;width: 100%;height: 130vh; padding-top: 5%;">
    <section class="vh-100">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-lg-12 col-xl-11">
                    <div class="card text-black" style="border-radius: 25px;">
                        <div class="card-body p-md-5">
                            <div class="row justify-content-center">
                                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                                    <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">{% trans 'Thông tin cá nhân' %}</p>

                                    <form method="POST" action="{% url 'users:user_profile' %}">
                                        {% csrf_token %}
                                        {% for field in form.visible_fields %}
                                        <div class="d-flex flex-row align-items-center mb-4">
                                            <div class="form-floating flex-fill mb-4">
                                                {{ field }}
                                                <label for="{{ field.name }}">{{ field.label }}</label>
                                                {% if field.errors %}
                                                {% for err in field.errors %}
                                                <span class="text-danger">{{ err }}</span>
                                                {% endfor %}
                                                {% endif %}
                                            </div>
                                        </div>
                                        {% endfor %}

                                        {% if form.non_field_errors %}
                                        {% for err in form.non_field_errors %}
                                        <div class="d-flex flex-row align-items-center mb-4">
                                            <div class="form-floating flex-fill mb-4">
                                                <span class="text-danger">{{ err }}</span>
                                            </div>
                                        </div>
                                        {% endfor %}
                                        {% endif %}

                                        {% if messages %}
                                        {% for message in messages %}
                                        {% if message.tags == 'success'%}
                                        <div class="d-flex flex-row align-items-center mb-4">
                                            <div class="form-floating flex-fill mb-4">
                                                <span class="text-success">{{ message }}</span>
                                            </div>
                                        </div>

                                        {% else %}
                                        <div class="d-flex flex-row align-items-center mb-4">
                                            <div class="form-floating flex-fill mb-4">
                                                <span class="text-danger">{{ message }}</span>
                                            </div>
                                        </div>
                                        {% endif %}
                                        {% endfor %}
                                        {% endif %}

                                        <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                                            <button type="submit" class="btn btn-primary btn-lg">{% trans 'Lưu' %}</button>
                                        </div>
                                    </form>
                                </div>
                                <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
                                    <img src="{% static 'users/images/register_image.png' %}" class="img-fluid"
                                        alt="Sample image">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
<!-- <div class="container">
    <div class="row">
        <div class="col l6">
            <h3>{% trans 'Thông tin cá nhân' %}</h3>
            <form method="POST" action="{% url 'users:user_profile' %}">
                {% csrf_token %}

                {% for field in form.visible_fields %}
                {{ field.label }}
                <div>
                    {{ field }}
                </div>
                {% if field.errors %}
                    <div class="card-panel red">
                        <span class="white-text">{{ field.errors }} </span>
                    </div>    
                {% endif%}  
                {% endfor %}

                {% if form.non_field_errors %}
                    {% for err in form.non_field_errors %}
                        <div class="card-panel red">
                            <span class="white-text">{{ err }}</span>
                        </div>
                    {% endfor %}
                {% endif %}

                {% if messages %}
                    {% for message in messages %}
                        {% if message.tags == 'success'%}
                            <div class="card-panel green">
                                <span class="white-text">{{ message }}</span>
                            </div>
                        {% else %}
                            <div class="card-panel red">
                                <span class="white-text">{{ message }}</span>
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                <button class="waves-effect waves-light btn-small red" type="submit">{% trans 'Lưu' %}</button>
            </form>
        </div>
    </div>
</div> -->

{% endblock content %}